<?php 

#These are all the files contained in the system 
$base_url = '/Aduk8/system/';
$base_dir_assets = $base_url.'assets/';
$path_to_user_domain = $base_url.'accounts/system-admin/';
$postDataFile = $path_to_user_domain.'includes/postData.php';

$dashboardFile = $path_to_user_domain.'dashboard.php';

//Registration
$new_school_url = $path_to_user_domain.'registration/school.php';
$new_system_admin_url = $path_to_user_domain.'registration/system-admin.php';
$new_subject_url = $path_to_user_domain.'registration/subjects.php';
$new_grade_level_url = $path_to_user_domain.'registration/grade-levels.php';

//Sign Out 
$logout_url = $base_url."includes/sign-out.php";
$signInFile = '/Aduk8/sign-in.php';

//globally used arrays
$genderOptions = array(
    "Male",
    "Female",
    "Rather Not Say",
    "Others"
) ;

$schoolInformation = array(
    "Primary School",
    "Junior Secondary School",
    "Senior Secondary School",
    "International School"
);

$staffOccupationOptions = array(
    "Principal",
    "Vice Principal",
    "Head Of House",
    "Teacher"
);
$staffOccupationPositionOptions = array(
    "Not Applicable",
    "Junior",
    "senior"
);

$nationalityOptions = array(
    "AF" => "Afghanistan",
    "AL" => "Albania",
    "DZ" => "Algeria",
    "US" => "United States",
    "AD" => "Andorra",
    "AO" => "Angola",
    "AG" => "Antigua and Barbuda",
    "AR" => "Argentina",
    "AM" => "Armenia",
    "AU" => "Australia",
    "AT" => "Austria",
    "AZ" => "Azerbaijan",
    "BS" => "Bahamas",
    "BH" => "Bahrain",
    "BD" => "Bangladesh",
    "BB" => "Barbados",
    "BY" => "Belarus",
    "BE" => "Belgium",
    "BZ" => "Belize",
    "BJ" => "Benin",
    "BT" => "Bhutan",
    "BO" => "Bolivia",
    "BA" => "Bosnia and Herzegovina",
    "BW" => "Botswana",
    "BR" => "Brazil",
    "BN" => "Brunei",
    "BG" => "Bulgaria",
    "BF" => "Burkina Faso",
    "BI" => "Burundi",
    "KH" => "Cambodia",
    "CM" => "Cameroon",
    "CA" => "Canada",
    "CV" => "Cape Verde",
    "CF" => "Central African Republic",
    "TD" => "Chad",
    "CL" => "Chile",
    "CN" => "China",
    "CO" => "Colombia",
    "KM" => "Comoros",
    "CD" => "Congo (Democratic Republic)",
    "CG" => "Congo (Republic)",
    "CR" => "Costa Rica",
    "HR" => "Croatia",
    "CU" => "Cuba",
    "CY" => "Cyprus",
    "CZ" => "Czech Republic",
    "DK" => "Denmark",
    "DJ" => "Djibouti",
    "DM" => "Dominica",
    "DO" => "Dominican Republic",
    "EC" => "Ecuador",
    "EG" => "Egypt",
    "SV" => "El Salvador",
    "GQ" => "Equatorial Guinea",
    "ER" => "Eritrea",
    "EE" => "Estonia",
    "ET" => "Ethiopia",
    "FJ" => "Fiji",
    "FI" => "Finland",
    "FR" => "France",
    "GA" => "Gabon",
    "GM" => "Gambia",
    "GE" => "Georgia",
    "DE" => "Germany",
    "GH" => "Ghana",
    "GR" => "Greece",
    "GD" => "Grenada",
    "GT" => "Guatemala",
    "GN" => "Guinea",
    "GW" => "Guinea-Bissau",
    "GY" => "Guyana",
    "HT" => "Haiti",
    "HN" => "Honduras",
    "HU" => "Hungary",
    "IS" => "Iceland",
    "IN" => "India",
    "ID" => "Indonesia",
    "IR" => "Iran",
    "IQ" => "Iraq",
    "IE" => "Ireland",
    "IL" => "Israel",
    "IT" => "Italy",
    "JM" => "Jamaica",
    "JP" => "Japan",
    "JO" => "Jordan",
    "KZ" => "Kazakhstan",
    "KE" => "Kenya",
    "KI" => "Kiribati",
    "KP" => "North Korea",
    "KR" => "South Korea",
    "KW" => "Kuwait",
    "KG" => "Kyrgyzstan",
    "LA" => "Laos",
    "LV" => "Latvia",
    "LB" => "Lebanon",
    "LS" => "Lesotho",
    "LR" => "Liberia",
    "LY" => "Libya",
    "LI" => "Liechtenstein",
    "LT" => "Lithuania",
    "LU" => "Luxembourg",
    "MK" => "North Macedonia",
    "MG" => "Madagascar",
    "MW" => "Malawi",
    "MY" => "Malaysia",
    "MV" => "Maldives",
    "ML" => "Mali",
    "MT" => "Malta",
    "MH" => "Marshall Islands",
    "MR" => "Mauritania",
    "MU" => "Mauritius",
    "MX" => "Mexico",
    "FM" => "Micronesia",
    "MD" => "Moldova",
    "MC" => "Monaco",
    "MN" => "Mongolia",
    "ME" => "Montenegro",
    "MA" => "Morocco",
    "MZ" => "Mozambique",
    "MM" => "Myanmar",
    "NA" => "Namibia",
    "NR" => "Nauru",
    "NP" => "Nepal",
    "NL" => "Netherlands",
    "NZ" => "New Zealand",
    "NI" => "Nicaragua",
    "NE" => "Niger",
    "NG" => "Nigeria",
    "NO" => "Norway",
    "OM" => "Oman",
    "PK" => "Pakistan",
    "PW" => "Palau",
    "PA" => "Panama",
    "PG" => "Papua New Guinea",
    "PY" => "Paraguay",
    "PE" => "Peru",
    "PH" => "Philippines",
    "PL" => "Poland",
    "PT" => "Portugal",
    "QA" => "Qatar",
    "RO" => "Romania",
    "RU" => "Russia",
    "RW" => "Rwanda",
    "KN" => "Saint Kitts and Nevis",
    "LC" => "Saint Lucia",
    "VC" => "Saint Vincent and the Grenadines",
    "WS" => "Samoa",
    "SM" => "San Marino",
    "ST" => "Sao Tome and Principe",
    "SA" => "Saudi Arabia",
    "SN" => "Senegal",
    "RS" => "Serbia",
    "SC" => "Seychelles",
    "SL" => "Sierra Leone",
    "SG" => "Singapore",
    "SK" => "Slovakia",
    "SI" => "Slovenia",
    "SB" => "Solomon Islands",
    "SO" => "Somalia",
    "ZA" => "South Africa",
    "SS" => "South Sudan",
    "ES" => "Spain",
    "LK" => "Sri Lanka",
    "SD" => "Sudan",
    "SR" => "Suriname",
    "SE" => "Sweden",
    "CH" => "Switzerland",
    "SY" => "Syria",
    "TW" => "Taiwan",
    "TJ" => "Tajikistan",
    "TZ" => "Tanzania",
    "TH" => "Thailand",
    "TL" => "Timor-Leste",
    "TG" => "Togo",
    "TO" => "Tonga",
    "TT" => "Trinidad and Tobago",
    "TN" => "Tunisia",
    "TR" => "Turkey",
    "TM" => "Turkmenistan",
    "TV" => "Tuvalu",
    "UG" => "Uganda",
    "UA" => "Ukraine",
    "AE" => "United Arab Emirates",
    "GB" => "United Kingdom",
    "UY" => "Uruguay",
    "UZ" => "Uzbekistan",
    "VU" => "Vanuatu",
    "VA" => "Vatican City",
    "VE" => "Venezuela",
    "VN" => "Vietnam",
    "YE" => "Yemen",
    "ZM" => "Zambia",
    "ZW" => "Zimbabwe"
);

$languageOptions = array(
    "Afrikaans" => "Afrikaans",
    "Albanian" => "Albanian",
    "Amharic" => "Amharic",
    "Arabic" => "Arabic",
    "Armenian" => "Armenian",
    "Azerbaijani" => "Azerbaijani",
    "Basque" => "Basque",
    "Belarusian" => "Belarusian",
    "Bengali" => "Bengali",
    "Bosnian" => "Bosnian",
    "Bulgarian" => "Bulgarian",
    "Burmese" => "Burmese",
    "Catalan" => "Catalan",
    "Cebuano" => "Cebuano",
    "Chinese (Simplified)" => "Chinese (Simplified)",
    "Chinese (Traditional)" => "Chinese (Traditional)",
    "Corsican" => "Corsican",
    "Croatian" => "Croatian",
    "Czech" => "Czech",
    "Danish" => "Danish",
    "Dutch" => "Dutch",
    "English" => "English",
    "Esperanto" => "Esperanto",
    "Estonian" => "Estonian",
    "Filipino" => "Filipino",
    "Finnish" => "Finnish",
    "French" => "French",
    "Frisian" => "Frisian",
    "Galician" => "Galician",
    "Georgian" => "Georgian",
    "German" => "German",
    "Greek" => "Greek",
    "Gujarati" => "Gujarati",
    "Haitian Creole" => "Haitian Creole",
    "Hausa" => "Hausa",
    "Hawaiian" => "Hawaiian",
    "Hebrew" => "Hebrew",
    "Hindi" => "Hindi",
    "Hmong" => "Hmong",
    "Hungarian" => "Hungarian",
    "Icelandic" => "Icelandic",
    "Igbo" => "Igbo",
    "Indonesian" => "Indonesian",
    "Irish" => "Irish",
    "Italian" => "Italian",
    "Japanese" => "Japanese",
    "Javanese" => "Javanese",
    "Kannada" => "Kannada",
    "Kazakh" => "Kazakh",
    "Khmer" => "Khmer",
    "Kinyarwanda" => "Kinyarwanda",
    "Korean" => "Korean",
    "Kurdish" => "Kurdish",
    "Kyrgyz" => "Kyrgyz",
    "Lao" => "Lao",
    "Latin" => "Latin",
    "Latvian" => "Latvian",
    "Lithuanian" => "Lithuanian",
    "Luxembourgish" => "Luxembourgish",
    "Macedonian" => "Macedonian",
    "Malagasy" => "Malagasy",
    "Malay" => "Malay",
    "Malayalam" => "Malayalam",
    "Maltese" => "Maltese",
    "Maori" => "Maori",
    "Marathi" => "Marathi",
    "Mongolian" => "Mongolian",
    "Nepali" => "Nepali",
    "Norwegian" => "Norwegian",
    "Nyanja (Chichewa)" => "Nyanja (Chichewa)",
    "Odia (Oriya)" => "Odia (Oriya)",
    "Pashto" => "Pashto",
    "Persian" => "Persian",
    "Polish" => "Polish",
    "Portuguese" => "Portuguese",
    "Punjabi" => "Punjabi",
    "Romanian" => "Romanian",
    "Russian" => "Russian",
    "Samoan" => "Samoan",
    "Scots Gaelic" => "Scots Gaelic",
    "Serbian" => "Serbian",
    "Sesotho" => "Sesotho",
    "Shona" => "Shona",
    "Sindhi" => "Sindhi",
    "Sinhala" => "Sinhala",
    "Slovak" => "Slovak",
    "Slovenian" => "Slovenian",
    "Somali" => "Somali",
    "Spanish" => "Spanish",
    "Sundanese" => "Sundanese",
    "Swahili" => "Swahili",
    "Swedish" => "Swedish",
    "Tagalog" => "Tagalog",
    "Tajik" => "Tajik",
    "Tamil" => "Tamil",
    "Tatar" => "Tatar",
    "Telugu" => "Telugu",
    "Thai" => "Thai",
    "Turkish" => "Turkish",
    "Turkmen" => "Turkmen",
    "Ukrainian" => "Ukrainian",
    "Urdu" => "Urdu",
    "Uyghur" => "Uyghur",
    "Uzbek" => "Uzbek",
    "Vietnamese" => "Vietnamese",
    "Welsh" => "Welsh",
    "Xhosa" => "Xhosa",
    "Yiddish" => "Yiddish",
    "Yoruba" => "Yoruba",
    "Zulu" => "Zulu"
);
